on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - name: build laptop
      run: |
        echo "Building a laptop"
        mkdir build
        touch build/computer.txt
        echo "Mainboard" > build/computer.txt
        cat build/computer.txt
        echo "Keyboard" >> build/computer.txt
        cat build/computer.txt

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: test laptop
      run: |
        test -f build/computer.txt
